### ISSUE TITLE
Doesn't build with Xcode  8.3.2 

### ISSUE THREAD

**Issue by ahalls** [openwhisk/WhiskSwiftTools#24]
I think there is some configuration step that I'm not doing ?

```
<unknown>:0: error: no such file or directory: '/Users/ahalls/Work/github/IBM-OpenWhisk/incubator-openwhisk-xcode/ZipArchive/SSZipArchive/SSZipArchive+Swift.swift'
```

**Comment by paulcastro** [comment]
You'll need [ZipArchive](https://github.com/ZipArchive/ZipArchive).

Further down in the README:

There is a dependency on an ObjC project ZipArchive. OS X CLI targets and frameworks don't play together very well. The "easiest" way to reference it is to add the code manually to WhiskSwiftTools. Clone ZipArchive and install per the documentations on the ZipArchive readme. Copy the SSZipArchive folder into the project folder and link to the libz library. WhiskSwiftTools includes bridging header file you can reference.

Are you just looking to deploy things?  You might be interested in [wskdeploy](https://github.com/apache/incubator-openwhisk-wskdeploy)

**Comment by troyibm** [comment]
I tried to follow your instructions here @paulcastro and got totally lost.  I notice that ZipArchive can be pulled in via Carthage.  Could that alleviate some of the problems if this project had a Cartfile?

**Comment by troyibm** [comment]
I also think things have changed in the ZipArchive project since the WhiskSwiftTools.xcproject file has been created as the aes and minizip directories are no longer parallel to each other.  The ZipArchive project has aes directory UNDER minizip.

**Comment by paulcastro** [comment]
Yes, it does appear that ZipArchive has changed.  I downloaded ZipArchive version 1.7 just now and I'm able to build wsktools using Xcode 8.3.3

I submitted a PR to update the README on this.

**Comment by troyibm** [comment]
so I could just download the 1.7 source zip, unzip into the incubator-openwhisk-xcode directory git clone created (change name of directory from ZipArchive-1.7 to ZipArchive), then open the WhiskSwiftTools.xcproject and do command+B and it will build?   (might be forgetting part with adding the libz library..)

**Comment by paulcastro** [comment]
Those are the steps that worked for me.

**Comment by dgrove-oss** [comment]
Closing as project is being archived.
